# Generated by Django 6.0 on 2026-01-01 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sector', models.CharField(choices=[('tech', 'Tech & SaaS'), ('green', 'Green & Energy'), ('food', 'Food & Beverage'), ('med', 'MedTech & Salute'), ('fashion', 'Fashion & Retail'), ('servizi', 'Servizi & Logistica'), ('ai', 'AI & Robotics'), ('agri', 'AgriTech'), ('fintech', 'Fintech')], max_length=20)),
                ('short_description', models.TextField(help_text='Testo breve per la card')),
                ('full_description', models.TextField(help_text='Descrizione dettagliata per il popup/pagina')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('affinity_score', models.IntegerField(default=0, help_text='Punteggio affinità (0-100)')),
                ('revenue_percent', models.DecimalField(decimal_places=2, help_text='Rendimento percentuale (es. 7.50)', max_digits=5)),
                ('funding_target', models.DecimalField(decimal_places=2, help_text='Obiettivo raccolta (es. 75000.00)', max_digits=12)),
                ('foundation_date', models.DateField(blank=True, null=True)),
                ('vat_number', models.CharField(max_length=20, verbose_name='Partita IVA')),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-affinity_score'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='companies/news/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.company')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
